---
- name: Install prerequisite packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ __jenkins__dependencies }}"

- name: Add the Jenkins repository to APT sources
  ansible.builtin.deb822_repository:
    name: jenkins
    types: ["deb"]
    uris: "{{ __jenkins_base_url }}"
    suites: "binary/"
    signed_by: "{{ __jenkins_gpg_key_url }}"
    enabled: true

- name: Install packages
  ansible.builtin.apt:
    update_cache: true
    name: jenkins
  notify: Start Jenkins service
