---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include ansible-role-jenkins"
      ansible.builtin.include_role:
        name: "../../../ansible-role-jenkins/" # noqa: role-name
